# docker-compose build --no-cache && docker-compose up --force-recreate

services:
  db:
    container_name: db
    image: postgres:14.8
    environment:
      POSTGRES_USER: sdf
      POSTGRES_PASSWORD: sdf
      PGDATA: /data/postgres
    volumes:
       - db_volume:/data/postgres
       - ./backend/database/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

  stated: 
    environment:
      - PORT=7766
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - API_KEY=XXX
      - DOMAIN=localhost
      - TEST=true
      - DELETE_DATA=true
    build: .
    ports:
      - '7766:7766'
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped


networks:
  postgres:
    driver: bridge

volumes:
    db_volume:
