# run npm run build in frontend folder first

FROM node:24-alpine 

WORKDIR /usr/src/stated

RUN apk update && apk add bind-tools

COPY backend/package*.json ./

RUN npm install 

COPY backend .
RUN echo 'export const cities = {"cities":[["Q1353","Delhi","Q668"]]}' > 'constants/cities.ts'
RUN echo 'export const subdivisions = [["AD", "02", "Canillo"]]' > 'constants/provinces_un_locode.ts'
RUN npm run build

ENV RETRY=false

CMD [ "node", "index.js"  ]
