// ["Country","Alpha-2 code","Alpha-3 code","Numeric","wikidata id"]
type CountryObject = string[]
export const countries: {countries: CountryObject[]} = {
    "countries" : [
        ["Afghanistan", "AF", "AFG", "004", "Q889"],
        ["Albania", "AL", "ALB", "008", "Q222"],
        ["Algeria", "DZ", "DZA", "012", "Q262"],
        ["American Samoa", "AS", "ASM", "016", ""],
        ["Andorra", "AD", "AND", "020", "Q228"],
        ["Angola", "AO", "AGO", "024", "Q916"],
        ["Anguilla", "AI", "AIA", "660", ""],
        ["Antarctica", "AQ", "ATA", "010", ""],
        ["Antigua and Barbuda", "AG", "ATG", "028", "Q781"],
        ["Argentina", "AR", "ARG", "032", "Q414"],
        ["Armenia", "AM", "ARM", "051", "Q399"],
        ["Aruba", "AW", "ABW", "533", "Q21203"],
        ["Australia", "AU", "AUS", "036", "Q408"],
        ["Austria", "AT", "AUT", "040", "Q40"],
        ["Azerbaijan", "AZ", "AZE", "031", "Q227"],
        ["Bahamas (the)", "BS", "BHS", "044", "Q778"],
        ["Bahrain", "BH", "BHR", "048", "Q398"],
        ["Bangladesh", "BD", "BGD", "050", "Q902"],
        ["Barbados", "BB", "BRB", "052", ""],
        ["Belarus", "BY", "BLR", "112", "Q184"],
        ["Belgium", "BE", "BEL", "056", "Q31"],
        ["Belize", "BZ", "BLZ", "084", "Q242"],
        ["Benin", "BJ", "BEN", "204", "Q962"],
        ["Bermuda", "BM", "BMU", "060", ""],
        ["Bhutan", "BT", "BTN", "064", "Q917"],
        ["Bolivia (Plurinational State of)", "BO", "BOL", "068", "Q750"],
        ["Bonaire, Sint Eustatius and Saba", "BQ", "BES", "535", ""],
        ["Bosnia and Herzegovina", "BA", "BIH", "070", "Q225"],
        ["Botswana", "BW", "BWA", "072", "Q963"],
        ["Bouvet Island", "BV", "BVT", "074", ""],
        ["Brazil", "BR", "BRA", "076", "Q155"],
        ["British Indian Ocean Territory (the)", "IO", "IOT", "086", ""],
        ["Brunei Darussalam", "BN", "BRN", "096", "Q921"],
        ["Bulgaria", "BG", "BGR", "100", "Q219"],
        ["Burkina Faso", "BF", "BFA", "854", "Q965"],
        ["Burundi", "BI", "BDI", "108", "Q967"],
        ["Cabo Verde", "CV", "CPV", "132", "Q1011"],
        ["Cambodia", "KH", "KHM", "116", "Q424"],
        ["Cameroon", "CM", "CMR", "120", "Q1009"],
        ["Canada", "CA", "CAN", "124", "Q16"],
        ["Cayman Islands (the)", "KY", "CYM", "136", ""],
        ["Central African Republic (the)", "CF", "CAF", "140", "Q929"],
        ["Chad", "TD", "TCD", "148", "Q657"],
        ["Chile", "CL", "CHL", "152", "Q298"],
        ["China", "CN", "CHN", "156", "Q148"],
        ["Christmas Island", "CX", "CXR", "162", ""],
        ["Cocos (Keeling) Islands (the)", "CC", "CCK", "166", ""],
        ["Colombia", "CO", "COL", "170", "Q739"],
        ["Comoros (the)", "KM", "COM", "174", "Q970"],
        ["Congo (the Democratic Republic of the)", "CD", "COD", "180", "Q974"],
        ["Congo (the)", "CG", "COG", "178", "Q971"],
        ["Cook Islands (the)", "CK", "COK", "184", "Q26988"],
        ["Costa Rica", "CR", "CRI", "188", "Q800"],
        ["Croatia", "HR", "HRV", "191", "Q224"],
        ["Cuba", "CU", "CUB", "192", "Q241"],
        ["Curaçao", "CW", "CUW", "531", ""],
        ["Cyprus", "CY", "CYP", "196", "Q229"],
        ["Czechia", "CZ", "CZE", "203", "Q213"],
        ["Côte d'Ivoire", "CI", "CIV", "384", "Q1008"],
        ["Denmark", "DK", "DNK", "208", "Q35"],
        ["Djibouti", "DJ", "DJI", "262", "Q977"],
        ["Dominica", "DM", "DMA", "212", "Q784"],
        ["Dominican Republic (the)", "DO", "DOM", "214", "Q786"],
        ["Ecuador", "EC", "ECU", "218", "Q736"],
        ["Egypt", "EG", "EGY", "818", "Q79"],
        ["El Salvador", "SV", "SLV", "222", "Q792"],
        ["Equatorial Guinea", "GQ", "GNQ", "226", ""],
        ["Eritrea", "ER", "ERI", "232", "Q986"],
        ["Estonia", "EE", "EST", "233", "Q191"],
        ["Eswatini", "SZ", "SWZ", "748", ""],
        ["Ethiopia", "ET", "ETH", "231", "Q115"],
        ["Falkland Islands (the) [Malvinas]", "FK", "FLK", "238", ""],
        ["Faroe Islands (the)", "FO", "FRO", "234", ""],
        ["Fiji", "FJ", "FJI", "242", "Q712"],
        ["Finland", "FI", "FIN", "246", "Q33"],
        ["France", "FR", "FRA", "250", "Q142"],
        ["French Guiana", "GF", "GUF", "254", ""],
        ["French Polynesia", "PF", "PYF", "258", ""],
        ["French Southern Territories (the)", "TF", "ATF", "260", ""],
        ["Gabon", "GA", "GAB", "266", ""],
        ["Gambia (the)", "GM", "GMB", "270", "Q1005"],
        ["Georgia", "GE", "GEO", "268", "Q230"],
        ["Germany", "DE", "DEU", "276", "Q183"],
        ["Ghana", "GH", "GHA", "288", "Q117"],
        ["Gibraltar", "GI", "GIB", "292", ""],
        ["Greece", "GR", "GRC", "300", "Q41"],
        ["Greenland", "GL", "GRL", "304", ""],
        ["Grenada", "GD", "GRD", "308", "Q769"],
        ["Guadeloupe", "GP", "GLP", "312", ""],
        ["Guam", "GU", "GUM", "316", ""],
        ["Guatemala", "GT", "GTM", "320", "Q774"],
        ["Guernsey", "GG", "GGY", "831", ""],
        ["Guinea", "GN", "GIN", "324", "Q1006"],
        ["Guinea-Bissau", "GW", "GNB", "624", "Q1007"],
        ["Guyana", "GY", "GUY", "328", "Q734"],
        ["Haiti", "HT", "HTI", "332", "Q790"],
        ["Heard Island and McDonald Islands", "HM", "HMD", "334", ""],
        ["Holy See (the)", "VA", "VAT", "336", ""],
        ["Honduras", "HN", "HND", "340", "Q783"],
        ["Hong Kong", "HK", "HKG", "344", ""],
        ["Hungary", "HU", "HUN", "348", "Q28"],
        ["Iceland", "IS", "ISL", "352", "Q189"],
        ["India", "IN", "IND", "356", "Q668"],
        ["Indonesia", "ID", "IDN", "360", "Q252"],
        ["Iran (Islamic Republic of)", "IR", "IRN", "364", "Q794"],
        ["Iraq", "IQ", "IRQ", "368", "Q796"],
        ["Ireland", "IE", "IRL", "372", "Q27"],
        ["Isle of Man", "IM", "IMN", "833", ""],
        ["Israel", "IL", "ISR", "376", "Q801"],
        ["Italy", "IT", "ITA", "380", "Q38"],
        ["Jamaica", "JM", "JAM", "388", "Q766"],
        ["Japan", "JP", "JPN", "392", "Q17"],
        ["Jersey", "JE", "JEY", "832", ""],
        ["Jordan", "JO", "JOR", "400", "Q810"],
        ["Kazakhstan", "KZ", "KAZ", "398", "Q232"],
        ["Kenya", "KE", "KEN", "404", "Q114"],
        ["Kiribati", "KI", "KIR", "296", "Q710"],
        ["Korea (the Democratic People's Republic of)", "KP", "PRK", "408", "Q423"],
        ["Korea (the Republic of)", "KR", "KOR", "410", "Q884"],
        ["Kuwait", "KW", "KWT", "414", ""],
        ["Kyrgyzstan", "KG", "KGZ", "417", "Q813"],
        ["Lao People's Democratic Republic (the)", "LA", "LAO", "418", "Q819"],
        ["Latvia", "LV", "LVA", "428", "Q211"],
        ["Lebanon", "LB", "LBN", "422", "Q822"],
        ["Lesotho", "LS", "LSO", "426", "Q1013"],
        ["Liberia", "LR", "LBR", "430", "Q1014"],
        ["Libya", "LY", "LBY", "434", "Q1016"],
        ["Liechtenstein", "LI", "LIE", "438", "Q347"],
        ["Lithuania", "LT", "LTU", "440", "Q37"],
        ["Luxembourg", "LU", "LUX", "442", ""],
        ["Macao", "MO", "MAC", "446", ""],
        ["Madagascar", "MG", "MDG", "450", "Q1019"],
        ["Malawi", "MW", "MWI", "454", "Q1020"],
        ["Malaysia", "MY", "MYS", "458", ""],
        ["Maldives", "MV", "MDV", "462", "Q826"],
        ["Mali", "ML", "MLI", "466", "Q912"],
        ["Malta", "MT", "MLT", "470", "Q233"],
        ["Marshall Islands (the)", "MH", "MHL", "584", "Q709"],
        ["Martinique", "MQ", "MTQ", "474", ""],
        ["Mauritania", "MR", "MRT", "478", "Q1025"],
        ["Mauritius", "MU", "MUS", "480", ""],
        ["Mayotte", "YT", "MYT", "175", ""],
        ["Mexico", "MX", "MEX", "484", "Q96"],
        ["Micronesia (Federated States of)", "FM", "FSM", "583", "Q702"],
        ["Moldova (the Republic of)", "MD", "MDA", "498", ""],
        ["Monaco", "MC", "MCO", "492", ""],
        ["Mongolia", "MN", "MNG", "496", "Q711"],
        ["Montenegro", "ME", "MNE", "499", "Q236"],
        ["Montserrat", "MS", "MSR", "500", ""],
        ["Morocco", "MA", "MAR", "504", "Q1028"],
        ["Mozambique", "MZ", "MOZ", "508", "Q1029"],
        ["Myanmar", "MM", "MMR", "104", "Q836"],
        ["Namibia", "NA", "NAM", "516", "Q1030"],
        ["Nauru", "NR", "NRU", "520", "Q697"],
        ["Nepal", "NP", "NPL", "524", "Q837"],
        ["Netherlands (the)", "NL", "NLD", "528", "Q55"],
        ["New Caledonia", "NC", "NCL", "540", ""],
        ["New Zealand", "NZ", "NZL", "554", "Q664"],
        ["Nicaragua", "NI", "NIC", "558", "Q811"],
        ["Niger (the)", "NE", "NER", "562", "Q1032"],
        ["Nigeria", "NG", "NGA", "566", "Q1033"],
        ["Niue", "NU", "NIU", "570", "Q34020"],
        ["Norfolk Island", "NF", "NFK", "574", ""],
        ["Northern Mariana Islands (the)", "MP", "MNP", "580", "Q16644"],
        ["Norway", "NO", "NOR", "578", "Q20"],
        ["Oman", "OM", "OMN", "512", "Q842"],
        ["Pakistan", "PK", "PAK", "586", "Q843"],
        ["Palau", "PW", "PLW", "585", "Q695"],
        ["Palestine, State of", "PS", "PSE", "275", ""],
        ["Panama", "PA", "PAN", "591", ""],
        ["Papua New Guinea", "PG", "PNG", "598", "Q691"],
        ["Paraguay", "PY", "PRY", "600", "Q733"],
        ["Peru", "PE", "PER", "604", "Q419"],
        ["Philippines (the)", "PH", "PHL", "608", "Q928"],
        ["Pitcairn", "PN", "PCN", "612", ""],
        ["Poland", "PL", "POL", "616", "Q36"],
        ["Portugal", "PT", "PRT", "620", "Q45"],
        ["Puerto Rico", "PR", "PRI", "630", ""],
        ["Qatar", "QA", "QAT", "634", "Q846"],
        ["Republic of North Macedonia", "MK", "MKD", "807", ""],
        ["Romania", "RO", "ROU", "642", "Q218"],
        ["Russian Federation (the)", "RU", "RUS", "643", "Q159"],
        ["Rwanda", "RW", "RWA", "646", "Q1037"],
        ["Réunion", "RE", "REU", "638", ""],
        ["Saint Barthélemy", "BL", "BLM", "652", ""],
        ["Saint Helena, Ascension and Tristan da Cunha", "SH", "SHN", "654", ""],
        ["Saint Kitts and Nevis", "KN", "KNA", "659", "Q763"],
        ["Saint Lucia", "LC", "LCA", "662", "Q760"],
        ["Saint Martin (French part)", "MF", "MAF", "663", ""],
        ["Saint Pierre and Miquelon", "PM", "SPM", "666", ""],
        ["Saint Vincent and the Grenadines", "VC", "VCT", "670", "Q757"],
        ["Samoa", "WS", "WSM", "882", "Q683"],
        ["San Marino", "SM", "SMR", "674", ""],
        ["Sao Tome and Principe", "ST", "STP", "678", "Q1039"],
        ["Saudi Arabia", "SA", "SAU", "682", "Q851"],
        ["Senegal", "SN", "SEN", "686", "Q1041"],
        ["Serbia", "RS", "SRB", "688", ""],
        ["Seychelles", "SC", "SYC", "690", "Q1042"],
        ["Sierra Leone", "SL", "SLE", "694", "Q1044"],
        ["Singapore", "SG", "SGP", "702", "Q334"],
        ["Sint Maarten (Dutch part)", "SX", "SXM", "534", "Q26273"],
        ["Slovakia", "SK", "SVK", "703", "Q214"],
        ["Slovenia", "SI", "SVN", "705", "Q215"],
        ["Solomon Islands", "SB", "SLB", "090", "Q685"],
        ["Somalia", "SO", "SOM", "706", "Q1045"],
        ["South Africa", "ZA", "ZAF", "710", "Q258"],
        ["South Georgia and the South Sandwich Islands", "GS", "SGS", "239", ""],
        ["South Sudan", "SS", "SSD", "728", "Q958"],
        ["Spain", "ES", "ESP", "724", ""],
        ["Sri Lanka", "LK", "LKA", "144", "Q854"],
        ["Sudan (the)", "SD", "SDN", "729", "Q1049"],
        ["Suriname", "SR", "SUR", "740", ""],
        ["Svalbard and Jan Mayen", "SJ", "SJM", "744", ""],
        ["Sweden", "SE", "SWE", "752", "Q34"],
        ["Switzerland", "CH", "CHE", "756", "Q39"],
        ["Syrian Arab Republic", "SY", "SYR", "760", "Q858"],
        ["Taiwan (Province of China)", "TW", "TWN", "158", "Q865"],
        ["Tajikistan", "TJ", "TJK", "762", "Q863"],
        ["Tanzania, United Republic of", "TZ", "TZA", "834", "Q924"],
        ["Thailand", "TH", "THA", "764", "Q869"],
        ["Timor-Leste", "TL", "TLS", "626", "Q574"],
        ["Togo", "TG", "TGO", "768", "Q945"],
        ["Tokelau", "TK", "TKL", "772", ""],
        ["Tonga", "TO", "TON", "776", ""],
        ["Trinidad and Tobago", "TT", "TTO", "780", "Q754"],
        ["Tunisia", "TN", "TUN", "788", "Q948"],
        ["Turkey", "TR", "TUR", "792", "Q43"],
        ["Turkmenistan", "TM", "TKM", "795", "Q874"],
        ["Turks and Caicos Islands (the)", "TC", "TCA", "796", ""],
        ["Tuvalu", "TV", "TUV", "798", "Q672"],
        ["Uganda", "UG", "UGA", "800", "Q1036"],
        ["Ukraine", "UA", "UKR", "804", "Q212"],
        ["United Arab Emirates (the)", "AE", "ARE", "784", "Q878"],
        ["United Kingdom of Great Britain and Northern Ireland (the)", "GB", "GBR", "826", "Q145"],
        ["United States Minor Outlying Islands (the)", "UM", "UMI", "581", ""],
        ["United States of America (the)", "US", "USA", "840", "Q30"],
        ["Uruguay", "UY", "URY", "858", "Q77"],
        ["Uzbekistan", "UZ", "UZB", "860", "Q265"],
        ["Vanuatu", "VU", "VUT", "548", "Q686"],
        ["Venezuela (Bolivarian Republic of)", "VE", "VEN", "862", "Q717"],
        ["Viet Nam", "VN", "VNM", "704", "Q881"],
        ["Virgin Islands (British)", "VG", "VGB", "092", ""],
        ["Virgin Islands (U.S.)", "VI", "VIR", "850", ""],
        ["Wallis and Futuna", "WF", "WLF", "876", ""],
        ["Western Sahara", "EH", "ESH", "732", ""],
        ["Yemen", "YE", "YEM", "887", "Q805"],
        ["Zambia", "ZM", "ZMB", "894", "Q953"],
        ["Zimbabwe", "ZW", "ZWE", "716", "Q954"],
        ["Åland Islands", "AX", "ALA", "248", ""]
    ]
}